name: CI
on:
  push:
    branches: [ kelton/ci-main ]
  pull_request:
    branches: [ kelton/ci-main ]
  workflow_dispatch:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: read 
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Make settings.xml file
        uses: s4u/maven-settings-action@v2.6.0
      - name: Build and test mu2
        run: mvn -B verify -P github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

