name: CI
on:
  push:
    branches: [ kelton/ci ]
  pull_request:
    branches: [ kelton/ci ]
  workflow_dispatch:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Make settings.xml file
        uses: s4u/maven-settings-action@v2.6.0
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build AFL proxy
        run: make
      - name: Build and test JQF
        run: mvn -B verify -P continuous-integration